### PR TITLE
Add CMake options for building tests and examples

### PR DESCRIPTION
**Pull request by Snowapril**
This revision includes:
* Add `BUILD_TESTS` option to enable building CubbyFlow test programs or not
* Add `BUILD_EXAMPLES` option to enable building CubbyFlow example programs or not

reference on https://github.com/glfw/glfw/blob/master/CMakeLists.txt#L25-L29

### CODE REVIEW

**Review by utilForever — APPROVED** [review]
LGTM. Thanks for your work! 🍡

**Comment by DveloperY0115** [comment]
Looks cool. It will provide broader options for those who want to get a hands-on on CubbyFlow without having to wait for building examples.

However, one thing I would like to mention: **Shouldn't the CI scripts be modified as we can now selectively build unit tests?** @Snowapril

**Review by DveloperY0115 — COMMENTED** [review]
Looks cool. It will provide broader options for those who want to get a hands-on on CubbyFlow without having to wait for building examples.

However, one thing I would like to mention: **Shouldn't the CI scripts be modified as we can now selectively build unit tests?** @Snowapril

**Comment by Snowapril** [comment]
@DveloperY0115 As their default value is `ON` there might be no difference in CI output I think 🤔

**Comment by DveloperY0115** [comment]
> @DveloperY0115 As their default value is `ON` there might be no difference in CI output I think 🤔

Oh, I see. Then it's up to user to toggle on & off. Thanks for clarification. Also, thank you for contributing.

**Review by DveloperY0115 — APPROVED** [review]
Everything looks fine :)

**Pull request merged**
