### PR TITLE
Modify CMakeLists.txt for selective CUDA builds

### PR DESCRIPTION
**Pull request by DveloperY0115**
Few changes were brought to `CMakeLists.txt` to let users decide whether CMake should build CUDA executable or not. 

Simply passing argument `-DENABLE_CUDA=ON` will tell CMake to check followings:
- Platform: **Building CUDA executable is only supported for Windows and Linux**)
- CUDA version: C++ 17 is only compatible with CUDA 11.0+

If all qualifications are met, CMake variable `DEFAULT_PROJECT_OPTIONS` will be modified to invoke `nvcc` during build.

### CODE REVIEW

**Review by utilForever — CHANGES_REQUESTED** [review]
You should check Codacy and CodeFactor issues. 🤔

**Comment by DveloperY0115** [comment]
> You should check Codacy and CodeFactor issues. 🤔

Yes, I noticed that. Since I'm not familiar with shell scripts, I'm thinking about the way how I can replace that part while following the rule.

**Comment by DveloperY0115** [comment]
Resolved issues related to code quality, such as 
1) missing shebang on top of the Linux script 
2) ambiguous/implicit if-then-else statement which can be misleading, cause of malfunctioning

**Review by utilForever — APPROVED** [review]
LGTM now. Thanks for your work! 🎉

**Pull request merged**
